version: '3.9'

services:
  postgres:
      image: postgres:15
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "5432:5432"

  server:
    build: './server'
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRECT=${CLIENT_SECRECT}
      - CALLBACK_URL=${CALLBACK_URL}
      - JWT_EXPIERS_IN=${JWT_EXPIERS_IN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

      - IS_SECURE_COOKIE=FALSE
    volumes:
      - ./server:/app
      - /app/node_modules